{{- if .Values.ingress.enabled -}}
{{- $fullName := include "lutho.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $annotationsPrefix := .Values.ingress.annotationsPrefix -}}
{{- $ingressHost := .Values.ingress.host -}}
{{- $ingressPath := .Values.ingress.path -}}
{{- $ingressPathType := .Values.ingress.pathType -}}
{{- $proxyTimeout := .Values.ingress.proxyTimeout -}}
{{- if and .Values.ingress.className (not (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .Values.ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .Values.ingress.annotations "kubernetes.io/ingress.class" .Values.ingress.className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "lutho.labels" . | nindent 4 }}
  annotations:
    {{ $annotationsPrefix }}/proxy-send-timeout: {{ $proxyTimeout | quote }}
    {{ $annotationsPrefix }}/proxy-read-timeout: {{ $proxyTimeout | quote }}
    # {{- if and (ne $ingressPath "") (ne $ingressPath "/") }}
    {{ $annotationsPrefix }}/use-regex: "true"
    {{ $annotationsPrefix }}/rewrite-target: /$2
    # {{- end }}
    {{- with .Values.ingress.annotations }}
    {{ tpl (toYaml .) $ }}
    {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  - host: {{ $ingressHost | quote }}
    http:
      paths:
      - path: {{ default "/" $ingressPath }}{{- if and (ne $ingressPath "") (ne $ingressPath "/") -}}(/|$)(.*){{- end -}}
        {{- if and $ingressPathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
        pathType: {{ $ingressPathType }}
        {{- end }}
        backend:
          {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
          service:
            name: {{ $fullName }}
            port:
              number: {{ $svcPort }}
          {{- else }}
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
          {{- end }}
{{- end }}
