{{ $fullname := include "lutho.fullname" . }}
{{ $serviceAccountName := include "lutho.serviceAccountName" . }}
{{ $releaseNamespace := .Release.Namespace }}
{{ $rbac := .Values.rbac }}
{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $fullname }}
{{- with .Values.rbac.rules }}
rules:
{{ tpl (toYaml .) $ }}
{{- end }}
---
{{- if $rbac.accessNamespaces -}}
{{- if $rbac.canListNamespaces -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $fullname }}-access-namespaces-list
rules:
- apiGroups:
  - ""
  resources:
  - "namespaces"
  verbs:
  - "list"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullname }}-access-namespaces-list
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $releaseNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ $fullname }}-access-namespaces-list
---
{{- end }}
{{- range $rbac.accessNamespaces }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullname }}
  namespace: {{ . }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $releaseNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ $fullname }}
---
{{- end }}
{{ else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $fullname }}
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $releaseNamespace }}
roleRef:
  kind: ClusterRole
  name: {{ $fullname }}
{{- end }}
{{- end }}
