apiVersion: v2
name: lutho
description: Manage Kubernetes based resources in a different way
home: https://kubeflame.github.io
type: application
version: 0.1.3
appVersion: "0.4.3-alpha"
keywords:
- lutho
- kubernetes
- kubeflame
maintainers:
- name: KubeFlame
  email: kubeflame@outlook.com
  url: https://github.com/kubeflame/charts
